-- Add missing columns to Bookings table to match Domain model

-- Check which columns already exist
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Bookings'
ORDER BY COLUMN_NAME;

-- Add BookingNumber column (unique identifier)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'BookingNumber')
BEGIN
    ALTER TABLE Bookings ADD BookingNumber NVARCHAR(20) NOT NULL DEFAULT '';
    CREATE UNIQUE INDEX IX_Bookings_BookingNumber ON Bookings(BookingNumber);
END;

-- Add PassengerCount column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'PassengerCount')
BEGIN
    ALTER TABLE Bookings ADD PassengerCount INT NOT NULL DEFAULT 1;
END;

-- Add SelectedSeats column (JSON for seat selection)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'SelectedSeats')
BEGIN
    ALTER TABLE Bookings ADD SelectedSeats NVARCHAR(MAX) NULL;
END;

-- Add SeatingArrangementImage column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'SeatingArrangementImage')
BEGIN
    ALTER TABLE Bookings ADD SeatingArrangementImage NVARCHAR(500) NULL;
END;

-- Add PricePerSeat column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'PricePerSeat')
BEGIN
    ALTER TABLE Bookings ADD PricePerSeat DECIMAL(18, 2) NOT NULL DEFAULT 0;
END;

-- Add TotalFare column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'TotalFare')
BEGIN
    ALTER TABLE Bookings ADD TotalFare DECIMAL(18, 2) NOT NULL DEFAULT 0;
END;

-- Add PlatformFee column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'PlatformFee')
BEGIN
    ALTER TABLE Bookings ADD PlatformFee DECIMAL(18, 2) NOT NULL DEFAULT 0;
END;

-- Add OTP column (6-digit verification code)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'OTP')
BEGIN
    ALTER TABLE Bookings ADD OTP NVARCHAR(6) NOT NULL DEFAULT '';
END;

-- Add QRCode column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'QRCode')
BEGIN
    ALTER TABLE Bookings ADD QRCode NVARCHAR(MAX) NULL;
END;

-- Add IsVerified column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'IsVerified')
BEGIN
    ALTER TABLE Bookings ADD IsVerified BIT NOT NULL DEFAULT 0;
END;

-- Add VerifiedAt column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'VerifiedAt')
BEGIN
    ALTER TABLE Bookings ADD VerifiedAt DATETIME2 NULL;
END;

-- Add CancellationType column (passenger, driver, system)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'CancellationType')
BEGIN
    ALTER TABLE Bookings ADD CancellationType NVARCHAR(20) NULL;
END;

-- Add CancelledAt column
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'CancelledAt')
BEGIN
    ALTER TABLE Bookings ADD CancelledAt DATETIME2 NULL;
END;

-- Add PaymentMethod column (cash, upi, card, wallet)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'PaymentMethod')
BEGIN
    ALTER TABLE Bookings ADD PaymentMethod NVARCHAR(20) NULL;
END;

-- Verify all columns were added
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Bookings'
ORDER BY COLUMN_NAME;

PRINT 'Bookings table schema updated successfully!';
