#!/bin/bash
# Display SSH key for GitHub Secrets setup

echo "=================================================="
echo "  GitHub Secrets Configuration Helper"
echo "=================================================="
echo ""
echo "You need to configure 3 GitHub Secrets:"
echo ""
echo "1. AZURE_VM_HOST = 57.159.31.172"
echo "2. AZURE_VM_USERNAME = akhileshallewar880"
echo "3. AZURE_VM_SSH_KEY = [SSH Private Key - see below]"
echo ""
echo "=================================================="
echo ""
echo "🔑 SSH Private Key (copy everything below):"
echo "=================================================="
cat server/ride_sharing_application/akhileshallewar880-key.pem
echo "=================================================="
echo ""
echo "📋 Steps to add secrets:"
echo "1. Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret with the exact name and value shown above"
echo ""
echo "⚠️  IMPORTANT for AZURE_VM_SSH_KEY:"
echo "   - Copy the ENTIRE key including -----BEGIN RSA PRIVATE KEY-----"
echo "   - Copy all lines including -----END RSA PRIVATE KEY-----"
echo "   - Paste as-is with all line breaks preserved"
echo ""
echo "=================================================="
